<style>
  p {
    max-width: 400px;
    text-align: center;
  }

  svg path {
    fill: var(--color);
  }

  * {
    font-family: 'Roboto', sans-serif;
    font-size: large;
  }

  .center {
    width: 100%;
    height: 100%;
  }

  .center,
  .icons {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
  }

  .icons {
    width: 190px;
    height: 190px;
    position: relative;

  }

  .animate-loop {
    animation-duration: var(--time);
    animation-iteration-count: infinite;
  }

  <?php if ($code == 503): ?>

    /* 503 */
    @keyframes rotate-r {
      from {
        transform: rotateZ(0deg);
      }

      to {
        transform: rotateZ(360deg);
      }
    }

    @keyframes rotate-break {
      0% {
        transform: rotateZ(0deg);
      }

      25% {
        transform: rotateZ(-180deg);
      }

      50% {
        transform: rotateZ(-180deg);
      }

      75% {
        transform: rotateZ(-360deg);
      }

      100% {
        transform: rotateZ(-360deg);
      }
    }


    .gear {
      position: absolute;
      animation-timing-function: linear;
    }

    #gear-1 {
      bottom: 0px;
      left: 0px;
      animation-name: rotate-r;
    }

    #gear-2 {
      right: 0px;
      top: 0px;
      animation-duration: calc(var(--time) * 2);
      animation-name: rotate-break;
    }

  <?php else: ?>

    /* *** */
    @keyframes levite {
      from {
        transform: translateY(0px);
      }

      50% {
        transform: translateY(-15px);
      }

      to {
        transform: translateY(0px);
      }
    }

    .levite {
      animation-duration: 4s;
      animation-timing-function: ease-in-out;
      animation-name: levite;
    }

  <?php endif ?>
</style>